/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "react-1-pEWwIJkcIf7xeXT36wTajVITJjla6qxwgs5CtSrRZZ7jvRg-hfe83YzorS1cDW58HYNd9xyaEeVww-zjSzHGF3u0Qpg3EQbAA9wDQEV3IP4ef7QPpeYPAjw-",
  "tt": "tt-1-MSBE6OAg5FuIUc-jva6fBoeRe23tvu25Am5d2GDewGA=",
  "version": "2020-11-20"
}

export default ebconfig;